### ISSUE TITLE
images within a blog post?

### ISSUE THREAD

**Issue by emilyeye** [muan/scribble#37]
Is there a way to include images within a blog post? When I preview my post files, I can see the images (see [here](https://github.com/emilyeye/emilyeye.github.io/blob/master/_posts/2016-01-01-image-test.md)). But when I look at the published post ([here](http://emilyeye.github.io/2013/05/06/image-test/)) I don't. Thanks in advance for any guidance you can offer -- I'm very new to this so I hope this question is useful to others in the future.

BTW, I love this design and template. Very cool and easy to use for a beginner like me.

**Comment by muan** [comment]
Thanks :)

You shouldn't be putting the images in `_posts`, instead, use the `images` folder on root. I see that you actually already have the same image in `images`, so just change the image URL to `/images/2016/1/asteroids.png` and it should work. (note the forward slash at the beginning of the URL).

On the GitHub page you can see it because the files haven't been processed by Jekyll.

:star:

Let me know if it doesn't work.
